language: ruby

rvm:
  - 2.0.0

before_script:
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create db:migrate db:schema:load

script:
  - bundle exec rspec

notifications:
  email:
    - amadeusfolego@gmail.com
    - playthecall@gmail.com

